spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# JWT configuration for tests
jwt:
  secret: test-secret-key-for-testing-purposes-only
  expiration: 86400000

# Disable security for tests if needed
spring.security.enabled: false